### ISSUE TITLE
Do CORS Unblock and CSP Unblock need both？

### ISSUE THREAD

**Issue by 921j** [balvin-perrie/Access-Control-Allow-Origin---Unblock#20]
Hello, thank you for writing such a good extension!
I am not a professional web developer, but a Rookie who occasionally wants to solve a lot of errors in the developer tools. I don’t really understand the difference between CORS and CPS.
I currently have your CORS Unblock 0.3.8 and CSP Unblock 0.1.1 installed on Chrome. I found that the latter has not been updated for a long time, and some options in CORS Unblock seem to be the same as CSP Unblock. Have you included the functions of the latter in the former? Now do I only need to install CORS Unblock?
Actually, I haven’t figured out the options in CORS Unblock. It would be great if only one extension is needed :) After all, similar names and similar functions can easily make people dizzy when studying.

**Comment by balvin-perrie** [comment]
You only need the "CORS Unblock" extension, which comes with all the necessary configurations. The other extension is specifically designed to address "CSP" issues.

**Comment by 921j** [comment]
Thanks!
