### ISSUE TITLE
support webdav http methods

### ISSUE THREAD

**Issue by TimDaub** [balvin-perrie/Access-Control-Allow-Origin---Unblock#5]
I'm using CORS unblock with WEBDAV (https://tools.ietf.org/html/rfc2518). I need it to enable the following http methods, taken from rfc2518 section 8

- PROPFIND
- PROPPATCH
- MKCOL
- GET
- HEAD
- POST
- DELETE
- PUT
- COPY
- MOVE
- LOCK

and headers, taken from section 9 "9  HTTP Headers for Distributed Authoring"

- DAV
- Depth
- Destiation
- If
- No-tag-list
- tagged-list
- lock-token
- overwrite
- status-uri
- timeout

In fact, I don't need all of those personally. But if possible, I'd like to be able to configure the CORS manipulation in the addon myself somehow. Is that possible?

**Comment by balvin-perrie** [comment]
Thanks for the report. Should ge fixed by 0.1.7 release.
