### ISSUE TITLE
Feature: Cookie support

### ISSUE THREAD

**Issue by framp** [balvin-perrie/Access-Control-Allow-Origin---Unblock#9]
Thanks for the useful extension!

It would be great to have support for sending cookies with the proxied requests.

Right now, if you're hitting an endpoint on a domain on which you have cookies, the request will not contain cookies for that domain

**Comment by balvin-perrie** [comment]
This extension does not have access to cookies. Just ask for cookies like:

```js
fetch(url, {
    credentials: 'same-origin', // include, same-origin, omit
})
```

**Comment by framp** [comment]
I see, I should have tried that! Thanks for the prompt answer

I noticed running chrome with disable-web-security you get the cookies out of the box (as long as they're not httpOnly), without needing to change the code.

(tbh I'm allowing other things too, not sure whether they were interfering with it or not)
```
❯ open -n -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --user-data-dir="/tmp/chrome_dev_test" --disable-web-security --allow-running-insecure-content --disable-features=SameSiteByDefaultCookies,SameSiteDefaultChecksMethodRigorously
```
